### PR TITLE
Using the stream that the dplay-apps use

### PR DESCRIPTION
**Pull request by ankjevel**
I didn't find any documentation on the plex-api, and have no background in python — so take this as is.

### CODE REVIEW

**Comment by meriko** [comment]
What was the problem with "http://www.dplay.se/?p=%s"?

If you're seeing something like "No URL service found for http://www.dplay.se/?p=12321", it is because you perhaps are not using the latest version of the Dplay URL service?

Some time ago, Plex updated the "auto updating function" for the Services.bundle(where the Dplay URL service is located), i.e. it only gets updated when you update Plex Media Server.

**Comment by ankjevel** [comment]
The problem I had was that the plugin did not work at all. I could see that there was shows, but no episodes. This did not work on my samsung tv(s), apple tv, android app or iphone app. And when checking my plugin logs — it said something about the plugin not getting the information needed.

But if you don't have this problem, just ignore my pull request. I just thought I'd share a solution that worked for me.

**Comment by meriko** [comment]
Strange... Can you please confirm that you're using newest Plex Media Server and get this problem? (Version 0.9.14.6.1620-e0b7243 Dec 23, 2015)

**Comment by Hexagon** [comment]
This plugin isn't working at all for me either, using chromecast from android. Installed plex from scratch three weeks ago, and is using the lastest version of this plugin. I can browse all seasons etc, but when i try to play a show i get an error message. All other plugins work just fine.

I havn't got the setup in reach right now, so i can't check the specifics. Just wanted to let you know more peaple have this problem and i don't think it should be dismissed.

**Comment by meriko** [comment]
Would be really great if you can confirm that you're using the latest version of Plex Media Server.

Since playback of channels using HLS(SVT, TV4 etc) + Chromecast stopped working with PMS v0.9.14.x(due to a bug in the updated transcoder/ffmpeg) I suspect you're on an older version?

Note that the 0.9.14.6 release was on 23 dec(first release of 0.9.14 for non PlexPass users), so if installing Plex three weeks ago(roughly around 15 dec) you would have got Plex Media Server v0.9.12.19 ...

**Comment by Hexagon** [comment]
Oh, It's correct that i have 0.9.12.19! 

My PMS seems to think that is the latest version ("Version 0.9.12.19  Uppdaterad"). But if all other swedish channels stopped working on chromecast i guess that's for the best :)

**Comment by meriko** [comment]
Yes I believe that PMS won't autoupdate to v0.9.14 since the change is really big, where is the v0.9.13 version? :)

For more information see this thread in the Plex forums:
https://forums.plex.tv/discussion/41453/kanal-5-play#latest

**Pull request closed without merging**
